name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore TechnicalTaskWithPlaywright.sln

      - name: Install Playwright CLI
        run: dotnet tool install --global Microsoft.Playwright.CLI

      - name: Update PATH
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH
        
      - name: Install Playwright Browsers
        run: playwright install

  test:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        browser: [chromium, firefox]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore TechnicalTaskWithPlaywright.sln

      - name: Install Playwright CLI
        run: dotnet tool install --global Microsoft.Playwright.CLI

      - name: Update PATH
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Install Playwright Browsers
        run: playwright install

      - name: Run tests
        run: dotnet test TechnicalTaskWithPlaywright.Tests/TechnicalTaskWithPlaywright.Tests.csproj --configuration Release --no-build --verbosity normal --filter "Browser=${{ matrix.browser }}"
