name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore TechnicalTaskWithPlaywright.sln

      - name: Install Playwright CLI
        run: dotnet tool install --global Microsoft.Playwright.CLI

      - name: Update PATH
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: List global tools
        run: dotnet tool list --global

      - name: Build the project
        run: dotnet build TechnicalTaskWithPlaywright.sln

      - name: List Playwright Cache
        run: ls -R $HOME/.cache/ms-playwright
        
      - name: Install Playwright Browsers
        run: playwright install

  test:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        test: 
          - DropDownTest
          - LoginTest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore TechnicalTaskWithPlaywright.sln

      - name: Run tests
        run: dotnet test Tests/Tests.csproj --configuration Release --verbosity normal --filter "FullyQualifiedName~${{ matrix.test }}"
